name: pmd

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  schedule:
    - cron: '32 10 * * 2'

permissions:
  contents: read

jobs:
  pmd-code-scan:
    permissions:
      contents: read       # for actions/checkout to fetch code
      security-events: write  # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read        # required for private repos by upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        # Pinned to a specific commit hash
        uses: actions/checkout@d1078b8f40a7f9a9b6d7a915f8b33b4eacb667a3

      - name: Set up JDK 21
        # Pinned commit hash for setup-java (update as needed)
        uses: actions/setup-java@08b1d73e9cc48b010243856045c2fa17d48e4e0a
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Run PMD
        id: pmd
        # Pin the PMD action to a specific commit hash. Replace <PMD_COMMIT_HASH> with the actual commit SHA.
        uses: pmd/pmd-github-action@<PMD_COMMIT_HASH>
        with:
          version: '7.0.0-rc4'
          rulesets: 'rulesets/java/quickstart.xml'
          sourcePath: 'src/main/java'
          analyzeModifiedFilesOnly: false

      - name: Upload SARIF file
        # Pinned commit hash for upload-sarif (example hash, update as needed)
        uses: github/codeql-action/upload-sarif@b5e338f7ad9e4a124b0a9d5e8e6a31c7d3e8d1f9
        with:
          sarif_file: pmd-report.sarif
