# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: pmd

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  schedule:
    - cron: '32 10 * * 2'

permissions:
  contents: read

jobs:
  pmd-code-scan:
    permissions:
      contents: read      # For actions/checkout to fetch code
      security-events: write  # For github/codeql-action/upload-sarif to upload SARIF results
      actions: read       # For private repositories: required for github/codeql-action/upload-sarif to get the action run status
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
=======
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up JDK 11
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
>>>>>>> 871b38052d568158e058a96f03ffbb3206ed6123
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Run PMD
        id: pmd
        uses: pmd/pmd-github-action@v2
        with:
          version: '7.0.0-rc4'
          rulesets: 'rulesets/java/quickstart.xml'
          sourcePath: 'src/main/java'
          analyzeModifiedFilesOnly: false

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@9e8d0789d4a0fa9ceb6b1738f7e269594bdd67f0 # v3.28.9
        with:
          sarif_file: pmd-report.sarif
